name: Scorecards Supply-chain Security

on:
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  analysis:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: "Run analysis"
        uses: ossf/scorecard-action@v2.1.0 
# or use this if required by GitHub:
# uses: ossf/scorecard-action@9c5f3efcdbec3ad17e3e96b0b894927a179e2cb7
        with:
          results_file: results.sarif
          results_format: sarif
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: SARIF file
          path: results.sarif
