name: Scorecards Supply-chain Security

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Scorecard via Docker
        run: |
          docker pull ossf/scorecard
          docker run -v $(pwd):/repo ossf/scorecard --repo=. --show-details --format=json > results.json
