name: OpenSSF Scorecard

on:
  push:
  schedule:
    - cron: '0 12 * * 1' # Weekly scan

permissions:
  id-token: write
  contents: read

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Scorecard
        uses: ossf/scorecard-action@v2.1.1
        with:
          results_file: results.sarif
          results_format: sarif

      - name: Upload Scorecard results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
